log stderr all;
router id 2.2.2.2;

protocol device {}

protocol kernel {
    ipv4 {
        export all;
    };
}

protocol ospf v2 {
    ipv4 {
        import all;
        export all;
    };
    area 0 {
        interface "eth_r1" { cost 10; type ptp; };
        interface "eth_r4" { cost 10; type ptp; };
        interface "lan"    { stub; };
    };
}
