log stderr all;
router id 5.5.5.5;

protocol device {}

protocol direct {
    ipv4;
    interface "lan";
}

protocol kernel {
    ipv4 {
        export all;
    };
}

protocol ospf v2 {
    ipv4 {
        import all;
        export all;
    };
    area 0 {
        interface "eth_r3" { cost 10; type ptp; };
        interface "eth_r4" { cost 10; type ptp; };
        interface "lan"    { stub; };
    };
}
