log stderr all;
router id 2.2.2.2;

protocol device {}

protocol direct {
    ipv4;
    interface "lan";
}

protocol kernel {
    ipv4 {
        export all;
    };
}

protocol rip {
    ipv4 {
        import all;
        export all;
    };
    interface "eth_r1" { mode multicast; version 2; };
    interface "eth_r4" { mode multicast; version 2; };
    interface "lan"    { passive; };
}
