log stderr all;
router id 4.4.4.4;

protocol device {}

protocol direct {
    ipv4;
    interface "lan";
}

protocol kernel {
    ipv4 {
        export all;
    };
}

protocol rip {
    ipv4 {
        import all;
        export all;
    };
    interface "eth_r2" { mode multicast; version 2; };
    interface "eth_r3" { mode multicast; version 2; };
    interface "eth_r5" { mode multicast; version 2; };
    interface "lan"    { passive; };
}
