log stderr all;
router id $(echo r4 | tr -dc '0-9').$(echo r4 | tr -dc '0-9').$(echo r4 | tr -dc '0-9').$(echo r4 | tr -dc '0-9');

protocol device {}

protocol direct {
    ipv4;
    interface "lan", "eth_*";
}

protocol kernel {
    ipv4 {
        export all;
    };
}

protocol rip {
    ipv4 {
        import all;
        export all;
    };
    interface "eth_*" { mode multicast; version 2; };
    interface "lan"   { passive; };
}
