log stderr all;
router id 1.1.1.1;

protocol device {}

protocol direct {
    ipv4;
    interface "lan", "eth_*";
}

protocol kernel {
    ipv4 {
        export all;
    };
}

protocol bgp ibgp_r3 {
    local 10.0.13.1 as 100;
    neighbor 10.0.13.2 as 100;
    ipv4 {
        next hop self;
        import all;
        export all;
    };
}

protocol bgp ebgp_r2 {
    local 10.0.12.1 as 100;
    neighbor 10.0.12.2 as 200;
    ipv4 {
        next hop self;
        import all;
        export all;
    };
}
