log stderr all;
router id 2.2.2.2;

protocol device {}

protocol direct {
    ipv4;
    interface "lan", "eth_*";
}

protocol kernel {
    ipv4 {
        export all;
    };
}

protocol bgp ebgp_r1 {
    local 10.0.12.2 as 200;
    neighbor 10.0.12.1 as 100;
    ipv4 {
        next hop self;
        import all;
        export all;
    };
}

protocol bgp ibgp_r4 {
    local 10.0.24.1 as 200;
    neighbor 10.0.24.2 as 200;
    ipv4 {
        next hop self;
        import all;
        export all;
    };
}
