log stderr all;
router id 3.3.3.3;

protocol device {}

protocol direct {
    ipv4;
    interface "lan", "eth_*";
}

protocol kernel {
    ipv4 {
        export all;
    };
}

protocol bgp ibgp_r1 {
    local 10.0.13.2 as 100;
    neighbor 10.0.13.1 as 100;
    ipv4 {
        next hop self;
        import all;
        export all;
    };
}

protocol bgp ebgp_r4 {
    local 10.0.34.1 as 100;
    neighbor 10.0.34.2 as 200;
    ipv4 {
        next hop self;
        import all;
        export all;
    };
}

protocol bgp ebgp_r5 {
    local 10.0.35.1 as 100;
    neighbor 10.0.35.2 as 300;
    ipv4 {
        next hop self;
        import all;
        export all;
    };
}
