log stderr all;
router id 5.5.5.5;

protocol device {}

protocol direct {
    ipv4;
    interface "lan", "eth_*";
}

protocol kernel {
    ipv4 {
        export all;
    };
}

protocol bgp ebgp_r3 {
    local 10.0.35.2 as 300;
    neighbor 10.0.35.1 as 100;
    ipv4 {
        next hop self;
        import all;
        export all;
    };
}

protocol bgp ebgp_r4 {
    local 10.0.45.2 as 300;
    neighbor 10.0.45.1 as 200;
    ipv4 {
        next hop self;
        import all;
        export all;
    };
}
